"use client";

import { useState, useEffect, useCallback } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import {
  ArrowLeftIcon,
  Bars3Icon,
  ClockIcon,
  CodeBracketIcon,
  DocumentTextIcon,
  EyeIcon,
  RectangleGroupIcon,
  TrashIcon,
  XMarkIcon,
} from "@heroicons/react/24/outline";
import { Sidebar } from "@/components/layout/Sidebar";
import { AccountMenu } from "@/components/layout/AccountMenu";
import { authClient } from "@/lib/auth/client";

export const dynamic = "force-dynamic";

interface ArtifactVersion {
  id: string;
  title: string;
  artifactType: "page" | "react-app" | "nextjs-bundle" | "document";
  chatId: string | null;
  createdAt: string;
  payload: Record<string, unknown>;
}

function typeLabel(type: ArtifactVersion["artifactType"]): string {
  const map: Record<string, string> = {
    page: "Page",
    "react-app": "React App",
    "nextjs-bundle": "Next.js Bundle",
    document: "Document",
  };
  return map[type] ?? type;
}

function typeIcon(type: ArtifactVersion["artifactType"]) {
  switch (type) {
    case "page":
      return <RectangleGroupIcon className="h-4 w-4" />;
    case "react-app":
    case "nextjs-bundle":
      return <CodeBracketIcon className="h-4 w-4" />;
    default:
      return <DocumentTextIcon className="h-4 w-4" />;
  }
}

function formatDate(dateString: string) {
  const d = new Date(dateString);
  return d.toLocaleString(undefined, {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

export default function ArtifactsPage() {
  const router = useRouter();
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [versions, setVersions] = useState<ArtifactVersion[]>([]);
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState<ArtifactVersion | null>(null);
  const [deleting, setDeleting] = useState<string | null>(null);
  const [toast, setToast] = useState<string | null>(null);

  useEffect(() => {
    authClient.getSession().then((s) => {
      if (!s?.data?.user) router.push("/login");
    });
  }, [router]);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/artifacts/versions?limit=100");
      if (res.ok) {
        const json = await res.json();
        setVersions(json.versions ?? []);
      }
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { load(); }, [load]);

  async function handleDelete(id: string) {
    if (!confirm("Delete this version?")) return;
    setDeleting(id);
    await fetch(`/api/artifacts/versions/${id}`, { method: "DELETE" });
    setVersions((prev) => prev.filter((v) => v.id !== id));
    if (selected?.id === id) setSelected(null);
    setToast("Version deleted");
    setDeleting(null);
    setTimeout(() => setToast(null), 3000);
  }

  return (
    <div className="flex h-screen overflow-hidden bg-quill-bg text-quill-text">
      {/* Mobile sidebar overlay */}
      {sidebarOpen && (
        <div className="fixed inset-0 z-40 flex lg:hidden">
          <div
            className="fixed inset-0 bg-black/50"
            onClick={() => setSidebarOpen(false)}
          />
          <div className="relative z-50 flex w-72 flex-col">
            <Sidebar onClose={() => setSidebarOpen(false)} />
          </div>
        </div>
      )}

      {/* Desktop sidebar */}
      <div className="hidden lg:flex lg:w-72 lg:flex-col lg:flex-shrink-0">
        <Sidebar />
      </div>

      {/* Main */}
      <div className="flex flex-1 flex-col min-w-0">
        {/* Header */}
        <div className="flex items-center gap-3 border-b border-quill-border px-4 py-3">
          <button
            className="lg:hidden rounded-lg p-2 hover:bg-quill-surface"
            onClick={() => setSidebarOpen(true)}
          >
            <Bars3Icon className="h-5 w-5" />
          </button>
          <Link
            href="/agent"
            className="rounded-lg p-2 hover:bg-quill-surface text-quill-muted hover:text-quill-text transition-colors"
          >
            <ArrowLeftIcon className="h-4 w-4" />
          </Link>
          <div className="flex-1 min-w-0">
            <h1 className="text-sm font-semibold truncate">Artifact History</h1>
            <p className="text-xs text-quill-muted truncate">
              Every artifact generated by Quill builder
            </p>
          </div>
          <AccountMenu />
        </div>

        {/* Body */}
        <div className="flex flex-1 overflow-hidden">
          {/* List panel */}
          <div className="w-full lg:w-80 flex-shrink-0 overflow-y-auto border-r border-quill-border">
            {loading ? (
              <div className="p-6 text-center text-quill-muted text-sm">Loading…</div>
            ) : versions.length === 0 ? (
              <div className="p-8 text-center">
                <ClockIcon className="mx-auto h-8 w-8 text-quill-muted mb-3" />
                <p className="text-sm font-medium">No artifacts yet</p>
                <p className="text-xs text-quill-muted mt-1">
                  Use the builder in agent chat to generate pages, apps, and documents.
                </p>
              </div>
            ) : (
              <ul className="divide-y divide-quill-border">
                {versions.map((v) => (
                  <li key={v.id}>
                    <button
                      onClick={() => setSelected(v)}
                      className={`w-full text-left px-4 py-3 hover:bg-quill-surface transition-colors ${
                        selected?.id === v.id ? "bg-quill-surface border-l-2 border-quill-accent" : ""
                      }`}
                    >
                      <div className="flex items-start justify-between gap-2">
                        <div className="flex items-center gap-2 min-w-0">
                          <span className="text-quill-muted flex-shrink-0">{typeIcon(v.artifactType)}</span>
                          <span className="text-sm font-medium truncate">{v.title}</span>
                        </div>
                        <button
                          onClick={(e) => { e.stopPropagation(); handleDelete(v.id); }}
                          disabled={deleting === v.id}
                          className="flex-shrink-0 p-1 rounded hover:bg-red-500/10 hover:text-red-400 text-quill-muted transition-colors"
                        >
                          <TrashIcon className="h-3.5 w-3.5" />
                        </button>
                      </div>
                      <div className="mt-1 flex items-center gap-2">
                        <span className="text-xs text-quill-muted bg-quill-surface-2 px-1.5 py-0.5 rounded">
                          {typeLabel(v.artifactType)}
                        </span>
                        <span className="text-xs text-quill-muted">{formatDate(v.createdAt)}</span>
                      </div>
                    </button>
                  </li>
                ))}
              </ul>
            )}
          </div>

          {/* Preview panel */}
          <div className="hidden lg:flex flex-1 flex-col overflow-hidden">
            {selected ? (
              <>
                <div className="flex items-center justify-between px-4 py-3 border-b border-quill-border">
                  <div>
                    <p className="text-sm font-semibold">{selected.title}</p>
                    <p className="text-xs text-quill-muted">
                      {typeLabel(selected.artifactType)} · {formatDate(selected.createdAt)}
                    </p>
                  </div>
                  <div className="flex items-center gap-2">
                    {selected.chatId && (
                      <Link
                        href={`/agent?chatId=${selected.chatId}`}
                        className="flex items-center gap-1 text-xs text-quill-muted hover:text-quill-text px-2 py-1 rounded border border-quill-border hover:bg-quill-surface transition-colors"
                      >
                        <EyeIcon className="h-3.5 w-3.5" /> Open chat
                      </Link>
                    )}
                    <button
                      onClick={() => setSelected(null)}
                      className="p-1 rounded hover:bg-quill-surface text-quill-muted"
                    >
                      <XMarkIcon className="h-4 w-4" />
                    </button>
                  </div>
                </div>
                <div className="flex-1 overflow-auto">
                  {selected.artifactType === "page" &&
                  typeof (selected.payload as Record<string, unknown>).html === "string" ? (
                    <iframe
                      srcDoc={String((selected.payload as Record<string, unknown>).html)}
                      sandbox="allow-scripts"
                      className="w-full h-full border-0"
                      title="Artifact preview"
                    />
                  ) : (
                    <pre className="p-4 text-xs text-quill-text font-mono whitespace-pre-wrap overflow-auto h-full">
                      {JSON.stringify(selected.payload, null, 2)}
                    </pre>
                  )}
                </div>
              </>
            ) : (
              <div className="flex flex-1 flex-col items-center justify-center gap-3 text-quill-muted">
                <EyeIcon className="h-10 w-10" />
                <p className="text-sm">Select a version to preview</p>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Toast */}
      {toast && (
        <div className="fixed bottom-4 right-4 z-50 rounded-lg bg-quill-surface border border-quill-border px-4 py-2 text-sm shadow-lg">
          {toast}
        </div>
      )}
    </div>
  );
}
