import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth/server";
import { headers as nextHeaders } from "next/headers";
import { getGithubConnectionByUserId, getGithubRepoSelectionsByUserId } from "@/lib/data/db-helpers";
import { publishFilesAsPullRequest } from "@/lib/integrations/github-app";
import { logAuditEvent } from "@/lib/data/audit-log";

export const dynamic = "force-dynamic";
export const maxDuration = 60;

function slugify(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40) || "artifact";
}

// POST /api/github/publish -- commit Canvas files to a new branch and open
// a pull request. NEVER pushes to the repo's default branch directly.
//
// Track C.3 PR 4/4 (ROADMAP.md, final piece). Same trust-scoping pattern as
// /api/github/pull (PR 3, #40): repoId is looked up against the user's own
// githubRepoSelections, never taken as an arbitrary repoFullName from the
// client. The full commit/branch/PR sequence was verified end-to-end
// against the real tovrr/quill-test installation from the VPS before this
// route was written (see publishFilesAsPullRequest in github-app.ts) --
// opened and then closed a real test PR (tovrr/quill-test#1) to confirm
// every step of the Git Data API sequence actually works.
export async function POST(req: NextRequest) {
  const session = await auth.api.getSession({ headers: await nextHeaders() });
  if (!session?.user?.id) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let body: {
    repoId?: string;
    files?: Record<string, string>;
    title?: string;
    commitMessage?: string;
    prBody?: string;
  };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  if (!body.repoId || !body.files || Object.keys(body.files).length === 0) {
    return NextResponse.json({ error: "repoId and a non-empty files map are required" }, { status: 400 });
  }

  const connection = await getGithubConnectionByUserId(session.user.id);
  if (!connection || !connection.accessToken) {
    return NextResponse.json({ error: "GitHub not connected" }, { status: 404 });
  }

  const selections = await getGithubRepoSelectionsByUserId(session.user.id);
  const selection = selections.find((s) => s.repoId === body.repoId);
  if (!selection) {
    return NextResponse.json({ error: "Repo not selected. Select it in Settings first." }, { status: 403 });
  }

  const baseBranch = selection.defaultBranch ?? "main";
  const title = body.title?.trim() || `Quill: ${selection.repoFullName} update`;
  const branchSlug = slugify(title);
  const newBranch = `quill/${branchSlug}-${Date.now().toString(36)}`;
  const commitMessage = body.commitMessage?.trim() || title;
  const prBody =
    body.prBody?.trim() ||
    "Generated by Quill AI. This branch was created from the repo's default branch and is opened here for review -- Quill never pushes directly to the default branch.";

  const result = await publishFilesAsPullRequest(
    connection.accessToken,
    selection.repoFullName,
    baseBranch,
    newBranch,
    body.files,
    commitMessage,
    title,
    prBody,
  );

  if (!result.ok) {
    return NextResponse.json({ error: result.error }, { status: 502 });
  }

  logAuditEvent({
    action: "github.publish.created",
    userId: session.user.id,
    metadata: { repoFullName: selection.repoFullName, branch: result.branch, prNumber: result.prNumber },
  });

  return NextResponse.json({
    ok: true,
    branch: result.branch,
    prUrl: result.prUrl,
    prNumber: result.prNumber,
  });
}
